CREATE OR REPLACE FUNCTION update_modified_column()
    RETURNS trigger AS
    $$
    begin NEW.updated_at
            = CURRENT_TIMESTAMP;
    RETURN NEW;
    END;
    $$
        language 'plpgsql';

CREATE TABLE tb_telemetry (
    telemetry_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sensor_id INTEGER NOT NULL,
    temperature DOUBLE PRECISION NOT NULL,
    humidity DOUBLE PRECISION NOT NULL,
    pressure DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    PRIMARY KEY (telemetry_id)
);

CREATE TRIGGER update_telemetry
    BEFORE UPDATE
    ON tb_telemetry
    FOR EACH ROW
    EXECUTE PROCEDURE update_modified_column();